# Generated by Django 3.2.8 on 2022-02-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Querie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('QueryDesc', models.CharField(max_length=2000)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
