# Generated by Django 3.2.8 on 2022-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='queries',
            field=models.ManyToManyField(blank=True, to='emails.Querie'),
        ),
    ]
